In [ ]:
print('test')

test


In [ ]:
!nvidia-smi


NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



## 00.Ppytorch fundamentals

In [ ]:
## 00.Ppytorch fundamentals

In [ ]:
import torch

print(torch.__version__)

1.12.1+cu113


##Introduction to Tensors
Creating Tensors

Pytorch Tensors are created with torch.tensor()

In [ ]:
#scalar

scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
scalar.ndim

0

In [ ]:
#get tensor back as python int
scalar.item()

7

In [ ]:
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [ ]:
vector.ndim


1

In [ ]:
vector.shape

torch.Size([2])

In [ ]:
#MATRIX
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
MATRIX


tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([ 9, 10])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,4,5],
                        [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [6, 7, 8]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [6, 7, 8]])

Random Tensors

`Start with random numbers -> look at random numbers -> Look at data -> update random numbers

In [ ]:
#create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_image_size_tensor = torch.rand(size=(224, 224, 3)) # hieght, width, color(RGB)
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [ ]:
random_image_size_tensor

tensor([[[0.1053, 0.2695, 0.3588],
         [0.1994, 0.5472, 0.0062],
         [0.9516, 0.0753, 0.8860],
         ...,
         [0.3421, 0.0172, 0.3031],
         [0.6576, 0.9813, 0.5840],
         [0.9902, 0.5978, 0.7888]],

        [[0.9008, 0.9180, 0.2201],
         [0.9597, 0.8029, 0.2662],
         [0.2614, 0.0806, 0.6256],
         ...,
         [0.3568, 0.1704, 0.6172],
         [0.0231, 0.6317, 0.7472],
         [0.0614, 0.1727, 0.1405]],

        [[0.9203, 0.9251, 0.5313],
         [0.9694, 0.3328, 0.0146],
         [0.6746, 0.6771, 0.9902],
         ...,
         [0.8345, 0.2273, 0.2865],
         [0.3940, 0.1418, 0.3650],
         [0.0908, 0.6902, 0.8538]],

        ...,

        [[0.5521, 0.6004, 0.1658],
         [0.1479, 0.8327, 0.2563],
         [0.1063, 0.4770, 0.2286],
         ...,
         [0.1551, 0.7881, 0.3759],
         [0.7442, 0.8621, 0.7548],
         [0.6381, 0.0106, 0.0893]],

        [[0.6170, 0.3402, 0.8306],
         [0.0705, 0.2111, 0.6203],
         [0.

Zeros and Ones

In [ ]:
#create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

## Create a range of Tensors and tensors-like

In [ ]:
#use torch.arange
one_to_ten = torch.arange(1, 11)
one_to_ten 


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.arange(start= 0, end = 1000, step = 77)

tensor([  0,  77, 154, 231, 308, 385, 462, 539, 616, 693, 770, 847, 924])

In [ ]:
#tensors-like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor Datatypes


In [ ]:
#float 32
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, #What dtype is tensor
                               device = None, #What device is tensor on --- cude, gpu, cpu
                               requires_grad = False) #whether or not to track gradients with tensor operations
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

THREE BIG ERRORS
1. Tensor not right datatype
2. Tensor not right shape
3. Tensor not on the right device


###Manipulating Tensors (tensor operations)

In [ ]:
# Add, subtract, multiple, divide, matrix multiplication
# torch.mul(tensor, 10) == tensor * 10


In [ ]:
#Matrix multiplication 
tensor = torch.tensor([1,2,3])
tensor


tensor([1, 2, 3])

In [ ]:
# tensor * tensor != matmul. matmul(tensor, tensor) is teh same as tensor @ tensor
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
# use %%time to print out the time of process

One of the most common errors in deep learning is a shape error


In [ ]:
tensor = torch.tensor([[1,2,3],
                       [4,5,6]])
tensor

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Tensor.T is transpose
tensor_a = tensor.T
tensor_a

tensor([[1, 4],
        [2, 5],
        [3, 6]])

Finding the min, max, mean, sum, etc of a tensor


In [ ]:
# create a tensor
x = torch.arange(0, 100, 10)
torch.min(x), x.min()


(tensor(0), tensor(0))

In [ ]:
%%time 
#So cool!
torch.max(x), x.max()

CPU times: user 72 µs, sys: 11 µs, total: 83 µs
Wall time: 86.3 µs


(tensor(90), tensor(90))

In [ ]:
# mean needs a float32 dtype
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

Reshaping, stacking, squeezing, unsqueezing

*reshaping -- it is what it sounds like. think Transposing

*view is like reshaping but shares the same memory as original tensor

*stacking - like concat but puts them ontop of eachother(vstack)

*squeeze --removes 1 dimension from a tensor

*unsqueeze - removes a dimension from a tensor

*permute return a view of the input with dimensions permuted(swapped) in a certain way

In [ ]:
# make a new tensor
x = torch.arange(1., 11.)
x, x.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]), torch.Size([10]))

In [ ]:
x_reshaped = x.reshape(10, 1)
x_reshaped, x_reshaped.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.]]), torch.Size([10, 1]))

In [ ]:
x_reshaped = x.reshape(5, 2) # 5 * 2 = 10 and the size of x is 10
x_reshaped, x_reshaped.shape

(tensor([[ 1.,  2.],
         [ 3.,  4.],
         [ 5.,  6.],
         [ 7.,  8.],
         [ 9., 10.]]), torch.Size([5, 2]))

In [ ]:
x_reshaped = x.reshape(1, 10)
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
z = x.view(1,10)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]]),
 torch.Size([1, 10]))

In [ ]:
#stack on top -- there is also vstack and hstack (look them up on your own)
x_stacked = torch.stack([x,x,x,x], dim=1) #this dim is for dimension. so think stacking it on a dimension. Like tilting? hard to think of
x_stacked, x_stacked.shape

(tensor([[ 1.,  1.,  1.,  1.],
         [ 2.,  2.,  2.,  2.],
         [ 3.,  3.,  3.,  3.],
         [ 4.,  4.,  4.,  4.],
         [ 5.,  5.,  5.,  5.],
         [ 6.,  6.,  6.,  6.],
         [ 7.,  7.,  7.,  7.],
         [ 8.,  8.,  8.,  8.],
         [ 9.,  9.,  9.,  9.],
         [10., 10., 10., 10.]]), torch.Size([10, 4]))

In [ ]:
#torch.squeeze - removes all single target dimensions from a tensor
x_reshaped.shape

torch.Size([1, 10])

In [ ]:
x_reshaped

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]])

In [ ]:
x_reshaped = x_reshaped.squeeze().shape

In [ ]:
x_reshaped

torch.Size([10])

squeeze() and unsqueeze(dim=0)

In [ ]:
tensor = torch.rand(size = (10, 222, 3))
tensor, tensor.shape

(tensor([[[0.5745, 0.9200, 0.3230],
          [0.8613, 0.0919, 0.3102],
          [0.9536, 0.6002, 0.0351],
          ...,
          [0.0931, 0.2550, 0.3019],
          [0.5889, 0.2446, 0.9089],
          [0.6501, 0.1374, 0.3852]],
 
         [[0.7029, 0.0650, 0.1280],
          [0.0728, 0.4482, 0.8423],
          [0.3919, 0.1191, 0.7616],
          ...,
          [0.2096, 0.2793, 0.1626],
          [0.5664, 0.3895, 0.0026],
          [0.1419, 0.7609, 0.7489]],
 
         [[0.3955, 0.9072, 0.2694],
          [0.4601, 0.4145, 0.8877],
          [0.7979, 0.1490, 0.8975],
          ...,
          [0.6153, 0.6509, 0.6609],
          [0.4575, 0.0230, 0.5170],
          [0.6960, 0.2174, 0.5862]],
 
         ...,
 
         [[0.3966, 0.9743, 0.3888],
          [0.2200, 0.3373, 0.7092],
          [0.5078, 0.7820, 0.0542],
          ...,
          [0.4245, 0.9513, 0.9191],
          [0.0986, 0.6056, 0.9114],
          [0.4178, 0.8171, 0.1655]],
 
         [[0.1067, 0.1978, 0.6560],
          [0

In [ ]:
tensor.shape

torch.Size([10, 222, 3])

In [ ]:
#permute changes dimensions locations
tensor_permuted = tensor.permute(2,0,1)
tensor_permuted.shape

torch.Size([3, 10, 222])

In [ ]:
tensor_permuted

tensor([[[0.5745, 0.8613, 0.9536,  ..., 0.0931, 0.5889, 0.6501],
         [0.7029, 0.0728, 0.3919,  ..., 0.2096, 0.5664, 0.1419],
         [0.3955, 0.4601, 0.7979,  ..., 0.6153, 0.4575, 0.6960],
         ...,
         [0.3966, 0.2200, 0.5078,  ..., 0.4245, 0.0986, 0.4178],
         [0.1067, 0.5661, 0.6651,  ..., 0.5013, 0.4158, 0.5014],
         [0.2004, 0.1584, 0.9456,  ..., 0.2916, 0.6106, 0.2491]],

        [[0.9200, 0.0919, 0.6002,  ..., 0.2550, 0.2446, 0.1374],
         [0.0650, 0.4482, 0.1191,  ..., 0.2793, 0.3895, 0.7609],
         [0.9072, 0.4145, 0.1490,  ..., 0.6509, 0.0230, 0.2174],
         ...,
         [0.9743, 0.3373, 0.7820,  ..., 0.9513, 0.6056, 0.8171],
         [0.1978, 0.1529, 0.9675,  ..., 0.5267, 0.8700, 0.6677],
         [0.6463, 0.0276, 0.5112,  ..., 0.9090, 0.8713, 0.3144]],

        [[0.3230, 0.3102, 0.0351,  ..., 0.3019, 0.9089, 0.3852],
         [0.1280, 0.8423, 0.7616,  ..., 0.1626, 0.0026, 0.7489],
         [0.2694, 0.8877, 0.8975,  ..., 0.6609, 0.5170, 0.

Indexing is Pytorch is the same as indexing in Numpy

In [ ]:
# Change between Pytorch and Numpy
# torch.from_numpy(ndarray)
# torch.Tensor.numpy()

In [ ]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array).type(torch.float32)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

default numpy dtype is float64, while default pytorch dtype is float32
so when changing between the 2. add 
`.type(torch.float32)`

In [ ]:
array.dtype, tensor.dtype

(dtype('float64'), torch.float32)

In [ ]:
#tensor to numpy
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.dtype, numpy_tensor.dtype #it kept the default dtype from the tensor (float32) 

(torch.float32, dtype('float32'))

Reproducability - taking the random out of random
random numbers -> tensor operations -> update random numbers   (kind of like Kmeans)

Random Seed - "flavor" the randomness

In [ ]:
torch.rand(3,3)

tensor([[0.6094, 0.0170, 0.2312],
        [0.3490, 0.4784, 0.5083],
        [0.6486, 0.1850, 0.8696]])

In [ ]:
random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7024, 0.6200, 0.5326, 0.8865],
        [0.9438, 0.4664, 0.1405, 0.1509],
        [0.4449, 0.5966, 0.9782, 0.7575]])
tensor([[0.9282, 0.8890, 0.3527, 0.7740],
        [0.1632, 0.2160, 0.4742, 0.5013],
        [0.5417, 0.9948, 0.5928, 0.1326]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#random but reproducable tensors use a seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3,4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3,4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


In [ ]:
#CPU
tensor = torch.tensor([1,2,3], device = "cpu")
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [ ]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [ ]:
#move tensor to gpu in available
tensor_on_gpu = tensor.to(device)
tensor_on_gpu.device

device(type='cpu')

In [ ]:
#move back to cpu
#if tensor is on gpu, cannot transform to numpy

In [ ]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
tensor_on_gpu

tensor([1, 2, 3])